### ISSUE TITLE
It Works!

### ISSUE THREAD

**Issue by oywino** [A6blpka/ha-wis-stt#1]
But I do get the following error when I try to use Assist:

![image](https://github.com/A6blpka/ha-wis-stt/assets/18447119/1a0f579a-2c60-4d92-8ab4-6f13a6f3ae47)

Is this to be expected?

**Comment by A6blpka** [comment]
What version of WIS are you using?

**Comment by oywino** [comment]
I'm not sure if this is the answer you're looking for:
![image](https://github.com/A6blpka/ha-wis-stt/assets/18447119/2aae9a14-0c55-4cc9-944a-7f5ea994fcb4)

**Comment by A6blpka** [comment]
Checked - it works with the public WIS instance.
You can compare the component settings with this one:
![изображение](https://github.com/A6blpka/ha-wis-stt/assets/46753414/db249625-9b39-4186-9495-a3f13120deda)

**Comment by oywino** [comment]
Sorry, I don't understand your reply.
If you have a solution for me, great - but what do I need to do?
(The screenshot your showing, where does it belong?)

**Comment by A6blpka** [comment]
These are the component's settings.
They show up when you add this component to your HA integrations (Settings > Integrations > Add Integration > WIS STT)

**Comment by oywino** [comment]
Aha! Now I understand 👍
(and I think I'm flipping between two threads on the same subject - sorry for that)
[Edit]
After properly inserting the https://infer.tovera.io/api/willow URL, everything works perfectly.
But why was there a default value in that field pointing to localhost:9000 ?
Does it mean it's possible to host WIS locally?

**Comment by A6blpka** [comment]
> Does it mean it's possible to host WIS locally?

Yep, you can find manul in the WIS repository: https://github.com/toverainc/willow-inference-server

If your problem has been resolved, please close the issue.

**Comment by oywino** [comment]
I will close the issue, but is there somewhere else we can continue the conversation in general?

**Comment by A6blpka** [comment]
> I will close the issue, but is there somewhere else we can continue the conversation in general?
[tg](https://t.me/a6blpka)

**Comment by oywino** [comment]
Solved by @A6blpka
